/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedTasteRouteImport } from './routes/_authenticated/taste'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMenusRouteImport } from './routes/_authenticated/menus'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'
import { Route as AuthenticatedBulkRouteImport } from './routes/_authenticated/bulk'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedMenuIndexRouteImport } from './routes/_authenticated/menu.index'
import { Route as AuthenticatedMenuIdRouteImport } from './routes/_authenticated/menu.$id'
import { Route as AuthenticatedEntryIdRouteImport } from './routes/_authenticated/entry.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasteRoute = AuthenticatedTasteRouteImport.update({
  id: '/taste',
  path: '/taste',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenusRoute = AuthenticatedMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulkRoute = AuthenticatedBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMenuIndexRoute = AuthenticatedMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuIdRoute = AuthenticatedMenuIdRouteImport.update({
  id: '/menu/$id',
  path: '/menu/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntryIdRoute = AuthenticatedEntryIdRouteImport.update({
  id: '/entry/$id',
  path: '/entry/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/add': typeof AuthenticatedAddRoute
  '/bulk': typeof AuthenticatedBulkRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/menus': typeof AuthenticatedMenusRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/taste': typeof AuthenticatedTasteRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/entry/$id': typeof AuthenticatedEntryIdRoute
  '/menu/$id': typeof AuthenticatedMenuIdRoute
  '/menu/': typeof AuthenticatedMenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/add': typeof AuthenticatedAddRoute
  '/bulk': typeof AuthenticatedBulkRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/menus': typeof AuthenticatedMenusRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/taste': typeof AuthenticatedTasteRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/entry/$id': typeof AuthenticatedEntryIdRoute
  '/menu/$id': typeof AuthenticatedMenuIdRoute
  '/menu': typeof AuthenticatedMenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/bulk': typeof AuthenticatedBulkRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/menus': typeof AuthenticatedMenusRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/taste': typeof AuthenticatedTasteRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/entry/$id': typeof AuthenticatedEntryIdRoute
  '/_authenticated/menu/$id': typeof AuthenticatedMenuIdRoute
  '/_authenticated/menu/': typeof AuthenticatedMenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/add'
    | '/bulk'
    | '/diary'
    | '/menus'
    | '/settings'
    | '/taste'
    | '/wishlist'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/entry/$id'
    | '/menu/$id'
    | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/add'
    | '/bulk'
    | '/diary'
    | '/menus'
    | '/settings'
    | '/taste'
    | '/wishlist'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/entry/$id'
    | '/menu/$id'
    | '/menu'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/add'
    | '/_authenticated/bulk'
    | '/_authenticated/diary'
    | '/_authenticated/menus'
    | '/_authenticated/settings'
    | '/_authenticated/taste'
    | '/_authenticated/wishlist'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/entry/$id'
    | '/_authenticated/menu/$id'
    | '/_authenticated/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taste': {
      id: '/_authenticated/taste'
      path: '/taste'
      fullPath: '/taste'
      preLoaderRoute: typeof AuthenticatedTasteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menus': {
      id: '/_authenticated/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AuthenticatedMenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulk': {
      id: '/_authenticated/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof AuthenticatedBulkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/menu/': {
      id: '/_authenticated/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof AuthenticatedMenuIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/$id': {
      id: '/_authenticated/menu/$id'
      path: '/menu/$id'
      fullPath: '/menu/$id'
      preLoaderRoute: typeof AuthenticatedMenuIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entry/$id': {
      id: '/_authenticated/entry/$id'
      path: '/entry/$id'
      fullPath: '/entry/$id'
      preLoaderRoute: typeof AuthenticatedEntryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedBulkRoute: typeof AuthenticatedBulkRoute
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedMenusRoute: typeof AuthenticatedMenusRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasteRoute: typeof AuthenticatedTasteRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedEntryIdRoute: typeof AuthenticatedEntryIdRoute
  AuthenticatedMenuIdRoute: typeof AuthenticatedMenuIdRoute
  AuthenticatedMenuIndexRoute: typeof AuthenticatedMenuIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedBulkRoute: AuthenticatedBulkRoute,
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedMenusRoute: AuthenticatedMenusRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasteRoute: AuthenticatedTasteRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedEntryIdRoute: AuthenticatedEntryIdRoute,
  AuthenticatedMenuIdRoute: AuthenticatedMenuIdRoute,
  AuthenticatedMenuIndexRoute: AuthenticatedMenuIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
